apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-clusters
  namespace: rhacm-policies
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
        - "OpenShift"
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: hub-cluster
  namespace: rhacm-policies
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
        - "true"
