apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: layers-app
  namespace: layers-app
  labels:
    app: layers-app
  annotations:
    apps.open-cluster-management.io/github-path: application
    apps.open-cluster-management.io/reconcile-option: replace
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  channel: layers/layers-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters
