kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: joe-view-development-namespace
  namespace: development
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: joe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view