apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sa-ownership-placement-rule.yaml
- sa-ownership-placement-binding.yaml
- sa-ownership-policy.yaml
patches:
- patch: |-
    - op: add
      path: /metadata/namespace
      value: rhacm-policies
  target:
    labelSelector: "policy=sa-ownership"
