kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhacm-edit-policy-greg
  namespace: policies-build
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: greg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhacm-edit-policy