apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: aks-cluster
  labels:
    name: aks-cluster
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: dev-clusters
    environment: dev
  annotations: {}
spec:
  hubAcceptsClient: true
---
apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: aks-cluster
stringData:
  autoImportRetry: "2"
  token: <token>
  server: aks-g-dns-68cg649e.hcp.eastus.azmk8s.io
type: Opaque
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: aks-cluster
  namespace: aks-cluster
spec:
  clusterName: aks-cluster
  clusterNamespace: aks-cluster
  clusterLabels:
    name: aks-cluster
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: dev-clusters
    environment: dev
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
