apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: liberty-rest
    version: v1
    app.kubernetes.io/part-of: liberty-rest
  name: liberty-rest
  namespace: liberty-rest-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: liberty-rest
      version: v1
  template:
    metadata:
      labels:
        app: liberty-rest
        version: v1
    spec:
      containers:
      - env:
        image: quay.io/marrober/liberty-rest:latest
        imagePullPolicy: Always
        name: liberty-rest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
