apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-edge-routes
  namespace: rhacm-policies
  labels:
    policy: edge-routes
placementRef:
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
  name: openshift-clusters
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: edge-routes
  
  