apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  resourceVersion: '266780459'
  name: cluster-1
  namespace: ztp-install
  ownerReferences:
    - apiVersion: cluster.open-cluster-management.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: ManagedCluster
      name: cluster-1
      uid: 79a63461-6c0c-448d-a3d5-114228ebcae9
  finalizers:
    - ran.openshift.io/cleanup-finalizer
spec:
  actions:
    afterCompletion:
      addClusterLabels:
        ztp-done: ''
      deleteObjects: true
      removeClusterLabels:
        - ztp-running
    beforeEnable:
      addClusterLabels:
        ztp-running: ''
  backup: false
  clusters:
    - cluster-1
  enable: true
  preCaching: false
  preCachingConfigRef: {}
  remediationStrategy:
    maxConcurrency: 1
    timeout: 240
