apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  annotations:
    open-cluster-management/created-via: hive
  creationTimestamp: "2026-07-15T06:16:49Z"
  finalizers:
  - managedcluster-import-controller.open-cluster-management.io/cleanup
  - managedclusterinfo.finalizers.open-cluster-management.io
  - open-cluster-management.io/managedclusterrole
  - cluster.open-cluster-management.io/resource-cleanup
  - cluster.open-cluster-management.io/api-resource-cleanup
  - managedcluster-import-controller.open-cluster-management.io/manifestwork-cleanup
  generation: 4
  labels:
    cloud: Amazon
    cluster.open-cluster-management.io/clusterset: dev-clusters
    clusterID: 1b09c6a6-eb25-4f0b-8cae-a1c3892059ee
    environment: dev
    feature.open-cluster-management.io/addon-application-manager: available
    feature.open-cluster-management.io/addon-cert-policy-controller: available
    feature.open-cluster-management.io/addon-cluster-proxy: available
    feature.open-cluster-management.io/addon-config-policy-controller: available
    feature.open-cluster-management.io/addon-governance-policy-framework: available
    feature.open-cluster-management.io/addon-managed-serviceaccount: available
    feature.open-cluster-management.io/addon-resource-usage-collect: available
    feature.open-cluster-management.io/addon-search-collector: available
    feature.open-cluster-management.io/addon-work-manager: available
    name: cluster-1
    openshiftVersion: 4.21.24
    openshiftVersion-major: "4"
    openshiftVersion-major-minor: "4.21"
    region: us-east-1
    vendor: OpenShift
    ztp-done: ""
  name: cluster-1
  resourceVersion: "266780443"
  uid: 79a63461-6c0c-448d-a3d5-114228ebcae9
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
  managedClusterClientConfigs:
  - caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNakNDQWhxZ0F3SUJBZ0lJT0RrZnJmS3FiaWd3RFFZSktvWklodmNOQVFFTEJRQXdOekVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1TRXdId1lEVlFRREV4aHJkV0psTFdGd2FYTmxjblpsY2kxc1lpMXphV2R1WlhJdwpIaGNOTWpZd056RTFNRFl4TnpVeldoY05Nell3TnpFeU1EWXhOelV6V2pBM01SSXdFQVlEVlFRTEV3bHZjR1Z1CmMyaHBablF4SVRBZkJnTlZCQU1UR0d0MVltVXRZWEJwYzJWeWRtVnlMV3hpTFhOcFoyNWxjakNDQVNJd0RRWUoKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUElnSVFLd1JZTkNqaVRvY2FDSWxycEJuTkN1VU9zeApuZC9zQUFTWnZ2dFFBb3doQzZadytYTXlaMC9hZFJGRlZ2WDVnbnQrNmtVVXpxWlZMMEdqVVl0Q0tEUjZwZGdBCmthdFNjOGxkRkJpd1FGbDQ3cUVkcEZsc3Y5ekFtbU9VamlIbHdaWWpQd3ZRUVhxbXAyWVFpSU1mRWx1ZENGcnQKR25hdnNEYTRrSWhuWGxyUjNnQXlJTk9jcFF5YVJ4ek1wOE9mOElsVEZrOU1CUWJlMEMwR1hiQ0V0STVWNkRhbQpxaXZRa25hRmh6VisvQkJaN1k4UldQa0lKTWxYeldUZVRrMTFMRkFYcStFdVh1aUg2QXFIQmFmSUJkMTFTbFdsCjB5MjQxL2lDaGlOMTF5bkZ6TmNwSnVtUnZXZ3Zudkw3MG5DR2dSRHgwTXFwVFE2cm5BNVJ6OGtDQXdFQUFhTkMKTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRklNcgp4UGZyOEJwZnM4S2VwdTB5UUVaZ3BqQmdNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUF6M0tDejRqblN0bEVTClhGbzVmVUxQRWJiWG1FNW44clV2NkJjL2RIazVkZ1JjNTdwL1hkVE43WE5HcjJIUE02T3lTUXk2OW11N2wxSVMKTW8wcGd1cTRoNHBxQkN4alQyWWsxdFpieVN0Ny94Q040V1NpSWVwd05QNklxcUxKNVUvckFib0VMUlpuekZsNQp2WFE3VWo1V1ZTQ2pDUHJpVlFWdzVzU3F3T0FEcFJwQ1F2U0xsVnl1OU5CWXAyRVhPT3RiMWpIRG90UDIveHVsCjhuZ1UvYmlYSG53eURFN1NsM2ZkM1QrV1BGSlVoRWFMMnV3ZHFrVzNMUHVNcHhVMktBc1YxU3ltbFJTQStGRDAKSCtDbTY1Mjd5Zmo0aUNOUlJwMCtRVkZDYy9xZXpXclE0VTAxY1hGV1ZndXR0LzhlVkttOVZkWHQ0RUFVOCtQTQpxWjBvdmhFRgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEUURDQ0FpaWdBd0lCQWdJSVZyT1UrWm9vQVFNd0RRWUpLb1pJaHZjTkFRRUxCUUF3UGpFU01CQUdBMVVFCkN4TUpiM0JsYm5Ob2FXWjBNU2d3SmdZRFZRUURFeDlyZFdKbExXRndhWE5sY25abGNpMXNiMk5oYkdodmMzUXQKYzJsbmJtVnlNQjRYRFRJMk1EY3hOVEEyTVRjMU0xb1hEVE0yTURjeE1qQTJNVGMxTTFvd1BqRVNNQkFHQTFVRQpDeE1KYjNCbGJuTm9hV1owTVNnd0pnWURWUVFERXg5cmRXSmxMV0Z3YVhObGNuWmxjaTFzYjJOaGJHaHZjM1F0CmMybG5ibVZ5TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxS2U2T1N3UlFDNjAKT2o5dzArUEl5TXBIemcxaTBxRXpGUkVpYXQvWk9FczY5aFBocUZ5a0FrOTJYYlluVndFVXN3ZlFsUGxFR0pvaQo2N1pKem1TSHNZc0dES3BsM3U2bTIza1ZYc2c0aWtNRWRBY3k1aFh4TzFjMlpBekhTMDR0aXlleVN2R3pUVmdXCndhYzhjUi8xWDBrQ2g5UFJrRS9QbHJCZ2tPazJ6MXhkNVVLN3VpRllHR3AxNy9CdDFEN0VpeGVXR1l0NldyL1YKRVg2QzVSY0d6Sk1pMFlKcUVSZnhQVkZPY1ZhdEFyQXFpV2FsWURnUGpyZTdOQUJXKzQvUnpXMnQ1QVN4eVZBdApIMU1vRjdxVnZ0eUwraHlyRjJYZGtwQW9TTlE3em9jOFdLWTlhdk54MkNiU21CUW4yeExJaUdCWmo2SjdISk0wCndHZjcyYzdxS3dJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVTQ5TFRhRVdtWTU2YnlaZy9waEZyUFE5QW1LTXdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUM5UU9LYUVKbWk2QWVkaXJGejF6WmVqZ0x2dy9QaWtBOFhNUk44MFNhSjBZVE5kWHVyYlMwd3BGaVNBCjRSMERxMDZ3SzlUbEd2NW8xeVdMWk5IMzRvRWNqVU9VWHpyREdhY2ZYL1RKSWY4dFIzM3dGN2lzRS9JUlFTb3YKQlJ1bTV0aDh0WFo1YmlxSUx3Z1ZRN0dlNFN5Q3ZDUHpMckhiM0hMRmdaVHg1T0ppempGU2ZZS2tUWFRxQmFXSAprTzV0Ykx4U0NSdWJhY2kwL2NPRVFUdUtjTVI1OUFHWHl0c3N1UXN0Yi9zNDV6UFhheFFHeFBVSnV6Tkc3ZDF5CmNHY1RKUUorNVZjc0U0bHBJYkNlLy9ZRzYwMkp0dU93QmlZUkx4dnRkemZzWE1IemwrQWoyV1IzTnlEbWlVZzAKemNSM0J2Qlp2T1QzQjNFbjJ1bkJ1RFlqcHZVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEVERDQ0FqU2dBd0lCQWdJSURHTTcwL05Dck80d0RRWUpLb1pJaHZjTkFRRUxCUUF3UkRFU01CQUdBMVVFCkN4TUpiM0JsYm5Ob2FXWjBNUzR3TEFZRFZRUURFeVZyZFdKbExXRndhWE5sY25abGNpMXpaWEoyYVdObExXNWwKZEhkdmNtc3RjMmxuYm1WeU1CNFhEVEkyTURjeE5UQTJNVGMxTTFvWERUTTJNRGN4TWpBMk1UYzFNMW93UkRFUwpNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUzR3TEFZRFZRUURFeVZyZFdKbExXRndhWE5sY25abGNpMXpaWEoyCmFXTmxMVzVsZEhkdmNtc3RjMmxuYm1WeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0MKQVFFQTdaSkxZY21FRS9xTHRkVjA2Nm5aV3l6ckFTS1ZoczViRzQwendKMVZ6cm9lWnZlcVRWVmI2ZXhLazBxeQpGbEo2U2V6QThFZXRRVTVkendDRXFPWFlrM1VGNTkwa0R3c21zT3JJaFI5K0RKNnhWNWF3UHlvMDJuN3JmL3BSCmJ3ZEp5TWZEY2VXaVkyaHRneHQ2WXJWOThwQW1TVSt5QVlhY2haa293SGFnOW9pSDNRNGkxOHQwSmNUWFlUQUQKQzY4Snpxdm9HM1kvMFgrdXg5YjQxS25Ydy9nZEhpdVhNNXlhV0J4amdaYkowZGx2WkFlcFFlWmpaVmN1SWNMSAp6K2F4dUtwN2FjZ0RQMC92ZWlwaVJLKzExanlUOHZFRmpaLzZLSC9ha1dHL0ZvN1JSY3VRYXE3WkdhNGV1LzdMCkNmbnB1OWlvQUx2RkF3cVV6emp1TlIzZVdRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVzRTFLd29iYWtXZENrcHpJVEQ3K240LzdWTjR3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIMm1JVkdvbE9CRi9wM1VJR2RSTGZuNXRSSzdBRGhMMEJscENVbi9iemJmCmRWVnI4Q2F2K0ZKSEdCMWhhMjhCK3VFVEhCaTU0cFFqSXlvbzhHQmszcEdGQ2dSckdjWU5IL2htaVgwTVh6eFcKM2NyK2EzUHJMYTZReDFjSzRxZGpjMkU0QTZGMENCSTg1MUxIdHVpYUpVRnRDOEh4OVlnUm9lOExnQmd5MXNmLwpNRXhwZjgreGZmMmVGRG9LajZGUWlSTEQ3SkpRT1RNS0ZUdVlRNWdSWGZrUG5YcEFlMTFHQWtBeVIzRjNqSW12Cmwvam8zTXA4VHF1aHArS3hNNWRKcXFmN1ZzZUVKSXEvTHA0U2RoTFBnQlBNa3FuVldiZEY4TFMvNjA4cDQwc28KTzBIU0FzZlJrOWdjUjgvQU1HUzRLdGNYMnkreUR4LzhKc1pyQWI0WlNVZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRGx6Q0NBbitnQXdJQkFnSUlLUldCTU54QWc4QXdEUVlKS29aSWh2Y05BUUVMQlFBd1dURlhNRlVHQTFVRQpBd3hPYjNCbGJuTm9hV1owTFd0MVltVXRZWEJwYzJWeWRtVnlMVzl3WlhKaGRHOXlYMnh2WTJGc2FHOXpkQzF5ClpXTnZkbVZ5ZVMxelpYSjJhVzVuTFhOcFoyNWxja0F4TnpnME1EazNNRGs1TUI0WERUSTJNRGN4TlRBMk16RTAKTUZvWERUTTJNRGN4TWpBMk16RTBNVm93V1RGWE1GVUdBMVVFQXd4T2IzQmxibk5vYVdaMExXdDFZbVV0WVhCcApjMlZ5ZG1WeUxXOXdaWEpoZEc5eVgyeHZZMkZzYUc5emRDMXlaV052ZG1WeWVTMXpaWEoyYVc1bkxYTnBaMjVsCmNrQXhOemcwTURrM01EazVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXZNWWIKZlJLTEdYaFR0Smd0eXpWdE0ycDI0VXVTQVM4ekZKWGRrL0t6R3dWc0YvcHduNjZDUHdVcmNLYUsxdDYvd0lZWAptVFRncEs1MmNELzdyWkFpdkNsa3pqSUF3OC96OFNkVEJ5NE5GUkJSQzJ0c2hOK3FyR3lzOW81Yk50SkI3cEY5CjdGMVVtOGo2ZkRGVTFCUTBvc2djaGZUMTZ6U1pBc0F1V1VvdWlhQjI5enE2U1J6Ym5pdy9xM3dLaWpQcm1nY3IKRVgrbmxUb096QzlraXJlL25DZkZBeGZkVFdJQUVIM01TVzdtNmNmL3lEbXlCMTZhR1pLdTZVcGNYN1lqbkMyUApvRXY0NVQ0YS9JM0lDNnBNOTFVWFRpeXZyTlJIamZ4MjQ2MjRqTUJFcXZFNTlOakJnVmZobHRicy9OMkg5eUZDCjZPWFk4NEpYUnpTVDRBL1pjd0lEQVFBQm8yTXdZVEFPQmdOVkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC8KQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVOE9oZ0puV1oyVWdmdit6MGJvOHVoc3dTcUJFd0h3WURWUjBqQkJndwpGb0FVOE9oZ0puV1oyVWdmdit6MGJvOHVoc3dTcUJFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHYjJMc1hSClhhQTlvUzVUdnY2VmJUNU5CMGpSeXlqOVhxdXVZWXB5YjN4eHJxQ1FsUW1oaUN0OFNwbk9ocWNkL1lUbjBaMjgKWlJvUjZSSCtyQmU1TnBvTDZ0elIxOGdQbUpaeGhhYW50T2VHbUptZXp4M3BEVFVRL2FxWHFuWThIbVZoYk9VQwpJbWxaTHNZTEYwYWpqeUdFa0VlSlE0cmJWWjBVck1vOXdqK2NBZ3V1NE1TMWxVRHpwVVNWWWZsTVFBSGIwMGtBCktYTWF5N3dpR1kxY3cwbWF6YzNRTWdKYmJIZXdqQkkydWZncDd5YXhlaVFwUm5CRTNqbGx2Qlhqd0s5UFRvNEUKQkRTVTVSdHVVREsyZTRXblBhVGlvR3A4cVJDSWlkQVBjWVh6YkExaXd0SWxiU3JIUXN3TWFZTTFaeTFJQ2liTQpiclB2UXVMUHd5RU94Mkk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoekNDQW0rZ0F3SUJBZ0lJWjU0STd6MzV5Qnd3RFFZSktvWklodmNOQVFFTEJRQXdKakVrTUNJR0ExVUUKQXd3YmFXNW5jbVZ6Y3kxdmNHVnlZWFJ2Y2tBeE56ZzBNRGszTWpBNU1CNFhEVEkyTURjeE5UQTJNek16TlZvWApEVEk0TURjeE5EQTJNek16Tmxvd016RXhNQzhHQTFVRUF3d29LaTVoY0hCekxtTnNkWE4wWlhJdE1TNXpZVzVrClltOTRNVGswTXk1dmNHVnVkR3hqTG1OdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0MKZ2dFQkFORmxRaFJKODBqSjk5V3V0VUEyM0dVWnZWZTk1RDF3b0ZtQUo4RHUwdzFJb3dNZjljQ0E3ZjFtd0hJTApGMlRRcFBVeEZ5c05NMUJVU21CcWhOWmhhNHpIWDlLbjROamlMNVIrS0kwdDJFb0xkdnhvUFNFdTFpaCtDbFh1CkpNZVU1SlorQXJnejJ0N3kwdGROdnoyaWo2U2h5SXBPODJuc0ZKNEE5L0JuK2Y5cGoxM3RDZlVMa2UrSkpGTkQKYnNDdndmWHVueE40U1BRL1lpeWxDTXdkaVpaa0hseS8rei9YQjIwSXhSajVVTzlZTFhWRVhjWVhyMFZmYXB4cwp5czg3SjdrTmZEUnZjMVpRUGtwQ0MwdWpDSW05bkNhVFJQSGYxdVc1M1RjMTJ5SWZMUFJGZGdsemVucWs0dUpkCnR2RGlnMDVJRFgySS8yZU1vNkY0NWZuR2FDTUNBd0VBQWFPQnF6Q0JxREFPQmdOVkhROEJBZjhFQkFNQ0JhQXcKRXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVOFJlYwpoR09pK2ZVMS8rOEYzaXBmTG15S1N5OHdId1lEVlIwakJCZ3dGb0FVME0vY2FlRkxwVWc3ZjZ6RjFvT3c0TkRSCnhZZ3dNd1lEVlIwUkJDd3dLb0lvS2k1aGNIQnpMbU5zZFhOMFpYSXRNUzV6WVc1a1ltOTRNVGswTXk1dmNHVnUKZEd4akxtTnZiVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBS05uWG8zUmRtYXlGdDlOcXR2TDNrUGVsRVpNdApmR0hpc0Y5OU8vTzRnUEVvSnU1Mjk3ckdidENoME9vaWY3NDc0K3NTbXBsUzN0L0RyQStOb3FGV3lMcEZGZkptCktaY1NEeHhtWjlBWDRxWmVNYXcyUzFpMEZIUjZyei9VaVh0akNzTnBsejBUbkF0bmxhWi9HYldrRmVlSEp2UGEKcG1QNmh1MDBVTlQzNTZXclZremN2UDVLRmVmcHRlRTRBd3NXTWQ3bzFzZEdOcGN1UWhQT1AzcHBwVVFMVjFobwozR0wrcSszZnhaREZRaStPeXJlZ1B4Y29jUmVLY09YTmszS2E3Wm5lL0JYTW9QRlMwcjhDNWkya1dVY3dMc3ErCmJEUURnRWd1dW5oVG5sMVc0bEZyTWpQenRaVFB3OUErMUdpUmtFVHdjNndUZnFzRTg3UE90c1dsM0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERERDQ0FmU2dBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBbU1TUXdJZ1lEVlFRRERCdHBibWR5ClpYTnpMVzl3WlhKaGRHOXlRREUzT0RRd09UY3lNRGt3SGhjTk1qWXdOekUxTURZek16TXpXaGNOTWpnd056RTAKTURZek16TTBXakFtTVNRd0lnWURWUVFEREJ0cGJtZHlaWE56TFc5d1pYSmhkRzl5UURFM09EUXdPVGN5TURrdwpnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDcTBsZDg0RUJVdnZ1ZE9wSVVnSzkrCll5UVNrTG5xSVQ4VERwK2V6N3lXMVVxclVBNVExb0crZ1lxYkU3eGVlbHN3K25jQ0FVcVFMeHBNK1IwWWZzN04KV3FUYWZVY0k4N3Vla0d4ZTB0aXdqSU1lVTQ5YmJaMTg1WEd0QWR0akZId0JEL1lTSFgxeUkrZFlSN1gxb3grUwpNRXI3c1JwcGJTSTdXWDE3TWFrcWlRWWNTRi9CTkRZcHd3ZmJlQ0FWNytPZ0NUdnJObU83UC9HT1Z3Y0dQU2RnClRISFF1TU04UjBRM3p5K2w0OFJPaENoN0Z6d0RGS0ROek9EQ21uaDlNbFovUFF3Q0w5Ly9xVlRKbW0zQ2NSRlYKZkJpcGIzSi96K3IvOHF2OGVEKzlvbks2cDd2V3I3VDd0blp6Wk9hUkxWSmZpVkR3VjBXb1EwRDBobzl1aXZ4UgpBZ01CQUFHalJUQkRNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHCkExVWREZ1FXQkJUUXo5eHA0VXVsU0R0L3JNWFdnN0RnME5IRmlEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUEKV3ppOTUzYm5uK1RQU1RyY09zSWtULy9Rdm16WEFtSFcvcUYzZ3ZqRnZDRHZWMVJndXJJRDZ2SzM2QTZaNGlLTQpmM2ZxTFlmckZBQXhJMko5dVZsTU1NeUNqa1h0cE4vZHB6ZG9RN3JtL3dOd3hja00wKzdUVlJhNkY3SWhONmlYCkpCSXpLVFplMlI1QjRGL1Z5bS9NZlo0YlUzZzBYYmRNZGdEV2hrWng0MlBEUXdNNU5NYlRpZTU0YUtBTllqV08KL0dBL1R3YnF0eGNXVWwyK0hyQnRENWE1c01QSzRGYmJMUFRpMVB2NWxoNHgvTG1oZDRCWkpmeldXZElVd0Q2SgpjRVQ3RUp4TXBiRnhKREwvTlAyVmFBR1lOTlp3WmtUQWpqMVlRY0xPQ3lEVWJpcElweWhWVjNFWFQ0d0FYenhDCkVEYUNhVUZFTlhwODQxbTZyUHg4alE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    url: https://api.cluster-1.sandbox1943.opentlc.com:6443
status:
  allocatable:
    cpu: "14"
    ephemeral-storage: "380073912916"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 59803580Ki
    pods: 1k
  capacity:
    core_worker: "4"
    cpu: "16"
    ephemeral-storage: 417066928Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 64407484Ki
    pods: 1k
    socket_worker: "0"
  clusterClaims:
  - name: apiserverurl.openshift.io
    value: https://api.cluster-1.sandbox1943.opentlc.com:6443
  - name: consoleurl.cluster.open-cluster-management.io
    value: https://console-openshift-console.apps.cluster-1.sandbox1943.opentlc.com
  - name: controlplanetopology.openshift.io
    value: HighlyAvailable
  - name: id.k8s.io
    value: 1b09c6a6-eb25-4f0b-8cae-a1c3892059ee
  - name: id.openshift.io
    value: 1b09c6a6-eb25-4f0b-8cae-a1c3892059ee
  - name: infrastructure.openshift.io
    value: '{"infraName":"cluster-1-4sp2g"}'
  - name: kubeversion.open-cluster-management.io
    value: v1.34.9
  - name: oauthredirecturis.openshift.io
    value: https://oauth-openshift.apps.cluster-1.sandbox1943.opentlc.com/oauth/token/implicit
  - name: platform.open-cluster-management.io
    value: AWS
  - name: product.open-cluster-management.io
    value: OpenShift
  - name: region.open-cluster-management.io
    value: us-east-1
  - name: schedulable.open-cluster-management.io
    value: "true"
  - name: version.openshift.io
    value: 4.21.24
  conditions:
  - lastTransitionTime: "2026-07-15T07:02:07Z"
    message: Import succeeded
    reason: ManagedClusterImported
    status: "True"
    type: ManagedClusterImportSucceeded
  - lastTransitionTime: "2026-07-15T06:16:50Z"
    message: Accepted by hub cluster admin
    reason: HubClusterAdminAccepted
    status: "True"
    type: HubAcceptedManagedCluster
  - lastTransitionTime: "2026-07-15T07:02:05Z"
    message: Managed cluster is available
    reason: ManagedClusterAvailable
    status: "True"
    type: ManagedClusterConditionAvailable
  - lastTransitionTime: "2026-07-15T07:02:04Z"
    message: The clock of the managed cluster is synced with the hub.
    reason: ManagedClusterClockSynced
    status: "True"
    type: ManagedClusterConditionClockSynced
  - lastTransitionTime: "2026-07-15T07:02:05Z"
    message: Managed cluster joined
    reason: ManagedClusterJoined
    status: "True"
    type: ManagedClusterJoined
  version:
    kubernetes: v1.34.9
