apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: must-gather-sa
  labels:
    policy: must-gather-sa
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: must-gather-sa
        spec:
          severity: medium
          object-templates-raw: |   
            {{- range $ns:= (lookup "v1" "Namespace" "" "" "").items }}   
            {{- if (contains "must-gather" $ns.metadata.name) }}
            {{- range $sa:= (lookup "v1" "ServiceAccount" $ns.metadata.name "" "").items }}
            {{- if (gt (now.Sub (mustToDate "2006-01-02T15:04:05Z07:00" $sa.metadata.creationTimestamp)).Hours 3.0) }}
            - complianceType: mustnothave 
              objectDefinition:
                kind: ServiceAccount
                apiVersion: v1
                metadata:
                  namespace: {{ $sa.metadata.namespace }}
                  name: {{ $sa.metadata.name }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
          remediationAction: inform