apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: dev-spaces
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: devspaces-operator-installation
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-devspaces
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: devspaces
                  namespace: openshift-operators
                spec:
                  channel: stable 
                  installPlanApproval: Automatic
                  name: devspaces
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
                  startingCSV: devspacesoperator.v3.25.0
            - complianceType: musthave
              objectDefinition:
                apiVersion: org.eclipse.che/v2
                kind: CheCluster
                metadata:
                  name: devspaces
                  namespace: openshift-devspaces
                spec:
                  components:
                    cheServer:
                      debug: false
                  containerRegistry: {}
                  devEnvironments:
                    startTimeoutSeconds: 300
                    secondsOfRunBeforeIdling: -1
                    maxNumberOfWorkspacesPerUser: -1
                    disableContainerRunCapabilities: true
                    containerBuildConfiguration:
                      openShiftSecurityContextConstraint: container-build
                    containerRunConfiguration:
                      containerSecurityContext:
                        procMount: Unmasked
                        capabilities:
                          add:
                            - SETGID
                            - SETUID
                        allowPrivilegeEscalation: true
                      openShiftSecurityContextConstraint: container-run
                    ignoredUnrecoverableEvents:
                      - FailedScheduling
                    defaultNamespace:
                      autoProvision: true
                      template: <username>-devspaces
                    secondsOfInactivityBeforeIdling: 3600
                    storage:
                      pvcStrategy: per-user