apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: openshift-clusters-dev-spaces
  namespace: rhacm-policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - key: vendor
            operator: In
            values:
            - "OpenShift"