apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: aks-dev
stringData:
  autoImportRetry: "5"
  # If you are using the kubeconfig file, add the following value for the kubeconfig file
  # that has the current context set to the cluster to import:
  kubeconfig: |- 
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1....Cg==
        server: https://aks-g-dns-68cg649e.hcp.eastus.azmk8s.io:443
      name: aks-g
    contexts:
    - context:
        cluster: aks-g
        user: clusterUser_openenv-tttgb_aks-g
      name: aks-g
    current-context: aks-g
    kind: Config
    preferences: {}
    users:
    - name: clusterUser_openenv-tttgb_aks-g
      user:
        client-certificate-data: LS0tLS....g==
        client-key-data: LS0tLS1CRUdJ....LS0tLS0K
        token: 6r16od....4ynxmf
type: Opaque