apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: gatekeeper-config
placementRef:
  name: all-openshift-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: gatekeeper-config
  kind: Policy
  apiGroup: policy.open-cluster-management.io
