apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-openshift-clusters
  labels:
    policy: default-sa
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
        - "OpenShift"
