apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: test
  namespace: rhacm-policies
  labels:
    policy: test
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-test-1
        spec:
          severity: medium
          object-templates-raw: |   
            {{- range $ns:= (lookup "v1" "Namespace" "" "" "").items }}   
              {{- if (contains "aa" $ns.metadata.name) }}
            - complianceType: musthave 
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ $ns.metadata.name }}
                  annotations:
                    containerName: '{{ fromConfigMap "simple-pipeline-1" "step-build" "containerName" }}'
                    containerImage: '{{ fromConfigMap "simple-pipeline-1" "step-build" "containerImage" }}'
              {{- end }}
            {{- end }}
          remediationAction: enforce

