apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: cm-generation-job-policy
  namespace: rhacm-policies
  labels:
    policy: test
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cm-generation-job-policy
        spec:
          severity: medium
          object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: batch/v1
              kind: CronJob
              metadata:
                name: generate-cm-job
                namespace: cm-1
              spec:
                schedule: "*/2 */1 * * *"
                jobTemplate:
                  spec:
                    template:
                      spec:
                        containers:
                        - name: generate-cm-job-container
                          command:
                            - /bin/bash
                            - -c
                            - |
                                #!/usr/bin/env bash
                                /workspace/bin/groovy -cp /workspace/groovy-json-4.0.26.jar config-map-generator.groovy pod/simple-pipeline-pr-lqkm8-build-pod simple-pipeline-1
                          image: quay.io/marrober/fedora-groovy-exec:v1
                          imagePullPolicy: Always
                        dnsPolicy: ClusterFirst
                        restartPolicy: Never
                        serviceAccount: sa-cm-job
                        terminationGracePeriodSeconds: 30
          remediationAction: enforce
