kind: ServiceAccount
apiVersion: v1
metadata:
  name: sa-cm-job
  namespace: cm-1
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cm-job-rolebinding-1
  namespace: cm-1
subjects:
  - kind: ServiceAccount
    name: sa-cm-job
    namespace: cm-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cm-job-rolebinding-2
  namespace: simple-pipeline-1
subjects:
  - kind: ServiceAccount
    name: sa-cm-job
    namespace: cm-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
