apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: load-balancer-annotation
  labels:
    policy: load-balancer-annotation
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: load-balancer-annotation
        spec:
          severity: medium
          object-templates-raw: |   
            {{- range $ns:= (lookup "v1" "Namespace" "" "" "svc-nodeport=allowed").items }}   
              {{- range $svc := (lookup "v1" "Service" $ns.metadata.name "" "").items }}
                {{- if (contains "LoadBalancer" $svc.spec.type) }}
            - complianceType: musthave 
              objectDefinition:
                kind: Service
                apiVersion: v1
                metadata:
                  namespace: {{ $svc.metadata.namespace }}
                  name: {{ $svc.metadata.name }}
                  annotations:
                    networking.gke.io/load-balancer-type: Internal
                {{- end }}
              {{- end }}
            {{- end }}
          remediationAction: enforce