apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: web-terminal
  namespace: rhacm-policies
  labels:
    policy: web-terminal
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: web-terminal
        spec:
          remediationAction: enforce
          complianceType: musthave
          severity: medium
          subscription:
            channel: fast
            name: web-terminal
            namespace: openshift-operators
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            startingCSV: web-terminal.v1.11.0
          upgradeApproval: None # None or Automatic
