apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: web-terminal
  namespace: rhacm-policies
  labels:
    policy: web-terminal
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: web-terminal
        spec:
          remediationAction: enforce
          complianceType: musthave
          severity: medium
          upgradeApproval: Automatic 
          subscription:
            channel: fast
            name: web-terminal
            namespace: openshift-web-terminal
            source: redhat-operators
            sourceNamespace: openshift-marketplace
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: web-terminal-crd-check
        spec:
          remediationAction: inform
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apiextensions.k8s.io/v1
                kind: CustomResourceDefinition
                metadata:
                  name: devworkspaces.workspace.devfile.io