apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: 03-deployer-sa
  labels:
    policy: deployer-sa
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: deployer-sa
        spec:
          evaluationInterval:
            compliant: 60s
            noncompliant: 60s
          customMessage:
            compliant: "No deployer service accounts are in use"
            noncompliant: "deployer service accounts are in use"
          severity: medium
          object-templates-raw: |   
            {{- range $sa := (lookup "v1" "ServiceAccount" "" "" "").items }}
              {{- if and (eq .spec.serviceAccountName "deployer") (hasPrefix "dev-" .metadata.namespace)  }}
              - complianceType: mustnothave 
                objectDefinition:
                  kind: ServiceAccount
                  apiVersion: v1
                  metadata:
                    name: {{ .metadata.name }}
                    namespace: {{ .metadata.namespace }}
              {{- end }}  
            {{- end }}
          remediationAction: inform