apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pipeline-sa-placement-binding.yaml
- pipeline-sa-policy.yaml
patches:
- patch: |-
    - op: add
      path: /metadata/namespace
      value: policies-dev
  target:
    labelSelector: "policy=pipeline-sa"
