apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../common
resources:
- subscription.yaml
patches:
- patch: |-
    - op: add
      path: /metadata/namespace
      value: rhacm-policies
  target:
    labelSelector: "policy=limit-range"
