apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-mcs
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclustersetbindings
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-mcs-biding-argo-sa
  namespace: policies-build
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  kind: ClusterRole
  name: gitops-mcs
  apiGroup: rbac.authorization.k8s.io