apiVersion: v1
kind: ServiceAccount
metadata:
  name: spotinst
  namespace: default
secrets:
  - name: spotinst-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: spotinst-secret
  annotations:
    kubernetes.io/service-account.name: spotinst
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spotinst-role
rules:
  - apiGroups: [""]
    resources:
      [
        "pods",
        "nodes",
        "replicationcontrollers",
        "events",
        "limitranges",
        "services",
      ]
    verbs: ["get", "delete", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spotinst-role-binding
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: spotinst
    namespace: default
