apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: ossm3-binding
placementRef:
  name: openshift-clusters-ossm3
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: ossm3-operator
  kind: Policy
  apiGroup: policy.open-cluster-management.io
