apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- limitrange-policy.yaml
- limitrange-placement-binding.yaml
- placement-rule.yaml
patches:
- patch: |-
    - op: add
      path: /metadata/namespace
      value: rhacm-policies
  target:
    labelSelector: "policy=limit-range"
