apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-limitrange-t-shirt
  labels:
    policy: limit-range-t-shirt
placementRef:
  name: limit-range-placement-t-shirt
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
- name: limitrange-t-shirt
  kind: Policy
  apiGroup: policy.open-cluster-management.io
