apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: liberty-rest-build
  namespace: liberty-rest-dev
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - liberty-rest-build
