apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: liberty-rest-build-latest
  namespace: liberty-rest-dev
spec:
  type: GitHub
  pathname: https://github.com/marrober/layers-deployment.git
