apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: pipelines-binding
  namespace: rhacm-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: pipelines-placement
subjects:
- name: pipelines-operator
  kind: Policy
  apiGroup: policy.open-cluster-management.io
