apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-default-sa
  labels:
    policy: default-sa
placementRef:
  name: dev-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: default-sa
  kind: Policy
  apiGroup: policy.open-cluster-management.io
